<div id="top"></div> 
# Table of contents
* <a href='#Submission-instructions'>Submission instructions</a>
* <a href="#A-short-introduction-to-LaTeX">A short introduction to LaTeX</a>
* <a href="#Some-useful-numpy-functions">Some useful numpy functions</a>
* <a href="#The-start-of-this-homework">The start of this homework</a>

# Submission instructions
Submit your .ipynb file through Sakai

Give us your name and PID. List the name and PID of your colaborators. 



<a href="#top">top</a>

# A short introduction to LaTeX

## Introduction
$ \LaTeX $ is a markup language to typeset documents. You can use it to express math compactly and make the layout of your documents beautiful. For the purpose of this class, we focus on the first piece, that is writing mathematical formulations. Jupyter implements a subset of $\LaTeX$. Therefore, you can use $ \LaTeX $ to answers the problems in the assignments.

## Two modes in latex that can typeset the formulations
1. Inline mode, start with an \$, end with an \$ (\$...\$). E.g. $a + b = \frac{1}{3}$
2. Display mode, start with two \$\$, end with two \$\$ (\$\$...\$\$). E.g. $$a+b=\frac{1}{3}$$

## Basic Maths
1. It is straight-forward for basic arithmetic operations. E.g. $+, - * /, a^b, a_b$.
2. $ \LaTeX$ already defined many useful symbols, macros, (or functions) to typeset the formulations. They start with \, such as \LaTeX is for the latex symbol. In some typeset functions you can give them parameters. E.g. \frac{1}{3} typesets one over three, where the thing within the first {} is nominator, and the thing within the second {} is denominator. {} also helps group thing within it together. Consider the difference between a\_b+1 ($a_b+1$) and a\_{b+1} ($a_{b+1}$)

## Useful symbols and functions
1. fraction, \frac{1}{3}. ($\frac{1}{3}$)
2. partial derivative, \partial. ($\partial$), Combined with 1), we have \frac{\partial f}{\partial x}. ($\frac{\partial f}{\partial x}$)
3. summation, \sum\_{i=1}^{N}. ($\sum_{i=1}^{N}$)
4. products, \prod\_{i=1}^{N}. ($\prod_{i=1}^{N}$)
5. indexing, w\_{i, j}. ($w_{i, j}$)
6. frequently used Greek letters \alpha, \beta, \gamma. ($\alpha, \beta, \gamma$)
7. gradient notation \nabla. ($\nabla$)
8. vector forms $\text{\\begin{bmatrix} x_{i, 1} \\ \vdots \\ x_{i, p+1}  \\end{bmatrix}}$. ($\begin{bmatrix} x_{i, 1} \\ \vdots \\ x_{i, p+1} \end{bmatrix}$) <br \>

<a href="#top">top</a>

# Some useful numpy functions

People usualy import numpy as the follow:

In [1]:
import numpy as np

Here we introduce some useful numpy functions that you might use in this homework.
* zeros <br \>
zeros generates a multi-dimensional array that contains all zeros. <br \>
    * Example: <br \>
    ** zeros( (3, 2) ) ** generates a 2d array of size 3\*2 (three rows and 2 columns) that contains zeros in all entries. <br \>
    ** zeros( (3, 2, 4) )** generates a 3d array of size 3\*2\*4 that also contains zero in all entries.
* ones <br \>
Similar to zeros, ones generates a multi-dimensional array that contains all ones. <br \>
* exp <br \>
exp takes exponential on each entry of the input. <br \>
    * Example: <br \>
    ** exp(3) ** computes $ e^3 $. <br \>
    ** exp( [1, 2, 3] ) ** computes $[ e^1, e^2, e^3]$.
* log <br \>
Similar to exp, log takes log on each entry of the input. Since log function is not defined on the values $<= 0$, if the input of log is like that, it will output nan or inf defined in numpy. <br \>
* sum <br \>
sum takes sum over an axis of the input array. <br \>
    * Example: please see the following code cell.

In [2]:
matrixA = np.arange(9).reshape(3, 3)
print( 'input array is a 3*3 matrix, values: \n', matrixA )
result1 = np.sum(matrixA, axis = 0)
result2 = np.sum(matrixA, axis = 1)
print( 'result 1 is ', result1 )
print( 'result 2 is ', result2 )

input array is a 3*3 matrix, values: 
 [[0 1 2]
 [3 4 5]
 [6 7 8]]
result 1 is  [ 9 12 15]
result 2 is  [ 3 12 21]


* dot <br \>
do dot-product of the two inputs (if they are vectors), or do matrix multiplication of the two inputs (if they are 2d arrays). In numpy if A and B are both arrays, A\*B computes the element-wise multiplication, not matrix multiplication. To use dot, the dimensions of the two inputs must be valid. <br \>
    * Example: please see the following code cells.

In [ ]:
#dot product examples
vector1 = np.array( [1, 2, 3] )
vector2 = np.array( [1, 2, 1] )
print( 'vecotr 1 is a length-3 vector, values: ', vector1 )
print( 'vecotr 2 is a length-3 vector, values: ', vector2 )
print( 'dot product of vecotr 1 and 2 is', np.dot(vector1, vector2) )
vector3 = np.array( [1, 2, 1, 2])
print( 'dot product of vecotr 1 and 3 generates error' )
np.dot(vector1, vector3)

In [4]:
#matrix multiplication examples
matrix1 = np.arange(6).reshape(2, 3)
matrix2 = np.ones(((3,1)))
print( 'matrix1 is a 2*3 matrix, values: \n ', matrix1 )
print( 'matrix2 is a 3*1 matrix, values: \n ', matrix2 )
print( 'matrix1 multiplies matrix2 is a 2*1 matrix: \n ', np.dot(matrix1, matrix2) )


matrix1 is a 2*3 matrix, values: 
  [[0 1 2]
 [3 4 5]]
matrix2 is a 3*1 matrix, values: 
  [[ 1.]
 [ 1.]
 [ 1.]]
matrix1 multiplies matrix2 is a 2*1 matrix: 
  [[  3.]
 [ 12.]]


* T <br \>
[numpy matrix variable].T, takes transpose of the input matrix variable.
    * Example: please see the following code cell <br \>
    

In [ ]:
matrix1 = np.ones( (4, 3) )
print( 'matrix dimension is',  matrix1.shape )
print( 'matrix dimension after transpose is', matrix1.T.shape )

<a href="#top">top</a>

# The start of this homework

# Import plotting utility

In [1]:
%matplotlib inline

import matplotlib
import matplotlib.pyplot as plt

# Download and load data

In [26]:
#download data
import time
import urllib
import os.path
import sys
versionName = sys.version_info
if versionName[0] == 2:
    import urllib as U
elif versionName[0] == 3:
    import urllib.request as U
start = time.time()
print("Should take at most 30 seconds")
if not os.path.isfile('train_data.pgz'):
    U.urlretrieve("https://sakai.unc.edu/access/content/group/c4f84923-328b-429b-a8dc-a340b0284e41/HW1/train_data.pgz", "train_data.pgz")
if not os.path.isfile('test_data.pgz'):
    U.urlretrieve("https://sakai.unc.edu/access/content/group/c4f84923-328b-429b-a8dc-a340b0284e41/HW1/test_data.pgz", "test_data.pgz")
if not os.path.isfile('vocab_list.pgz'):
    U.urlretrieve( "https://sakai.unc.edu/access/content/group/c4f84923-328b-429b-a8dc-a340b0284e41/HW1/vocab_list.pgz", "vocab_list.pgz" );
end = time.time()
print("Time elapsed (seconds):", end-start)

Should take at most 30 seconds
Time elapsed (seconds): 0.0009288787841796875


In [12]:
#load data
try:
    import cPickle as pickle
    kwargs = {}
except:
    import _pickle as pickle
    kwargs = {'encoding':'bytes'}
    
import gzip
import numpy as np
start = time.time()
print("Should take about 15 seconds")
train_data, train_label = pickle.load( gzip.open( "train_data.pgz", "rb" ), **kwargs )
train_label = np.asarray(train_label)
test_data = pickle.load( gzip.open( "test_data.pgz", "rb" ),**kwargs )
vocab_list = pickle.load( gzip.open( "vocab_list.pgz", "rb" ),**kwargs )
end = time.time()
print("Time elapsed (seconds):", end-start)

Should take about 15 seconds
Time elapsed (seconds): 9.555619716644287


In [8]:
#Consider using small set of the data
trainData = train_data[:10000, :]
validData = train_data[10000:15000, :]
trainLabel = train_label[:10000]
validLabel = train_label[10000:15000]
testData = test_data[:10000, :]
print( vocab_list )

['able', 'absolutely', 'across', 'act', 'acted', 'acting', 'action', 'actor', 'actors', 'actress', 'actual', 'actually', 'add', 'admit', 'adult', 'adventure', 'age', 'ago', 'agree', 'air', 'almost', 'alone', 'along', 'already', 'also', 'although', 'always', 'amazing', 'america', 'american', 'among', 'amusing', 'animated', 'animation', 'annoying', 'another', 'anyone', 'anything', 'anyway', 'apart', 'apparently', 'appear', 'appears', 'appreciate', 'around', 'art', 'ask', 'atmosphere', 'attempt', 'attempts', 'attention', 'audience', 'average', 'avoid', 'away', 'awful', 'baby', 'back', 'background', 'bad', 'badly', 'band', 'based', 'basic', 'basically', 'battle', 'beautiful', 'beauty', 'became', 'become', 'becomes', 'begin', 'beginning', 'begins', 'behind', 'believable', 'believe', 'ben', 'best', 'better', 'beyond', 'big', 'biggest', 'bill', 'bit', 'bizarre', 'black', 'blood', 'body', 'book', 'books', 'bored', 'boring', 'box', 'boy', 'boys', 'break', 'brilliant', 'bring', 'brings', 'britis

In [9]:
train_data.mean(0)

array([  1.01049613e-15,  -5.65727465e-16,   2.07511563e-15,
        -1.25034871e-15,   8.93827234e-16,   2.09658957e-16,
         1.24238841e-15,   1.42255097e-16,   1.64055436e-15,
        -9.47040224e-16,   2.49471777e-15,  -2.77537993e-16,
        -1.35806033e-15,  -2.28569386e-16,  -4.80685491e-16,
         4.10660395e-17,  -1.47469592e-15,  -2.29052333e-16,
         1.79992687e-15,   5.72459857e-16,  -7.98441313e-16,
        -7.43938244e-17,  -1.37430067e-15,  -4.51683135e-16,
         5.87072613e-16,  -1.25504496e-15,   7.40705275e-16,
        -1.24832367e-15,  -2.98550518e-15,  -2.53230104e-15,
        -2.07554862e-15,  -1.01518793e-17,   5.15988363e-16,
        -3.17301740e-16,  -1.22530652e-15,   1.63173031e-15,
        -1.02405640e-15,  -4.67292871e-16,  -3.91819910e-17,
        -1.19720900e-15,   2.47845300e-15,  -1.31523681e-16,
         6.25703933e-16,   2.51556553e-16,   1.78223658e-15,
        -1.40591760e-15,   7.31237293e-16,  -8.80038264e-16,
        -8.96323016e-16,

<div id="top_of_steps"></div>
# Steps
1. <a href="#Implement-logistic-regression-likelihood.">Implement logistic regression likelihood.</a>
2. <a href="#Compute-derivative-of-logistic-regression.">Compute derivative of logistic regression.</a>
3. <a href="#Check-gradient.">Check gradient.</a>
4. <a href="#Tweak-gradient-ascent-code.">Tweak gradient ascent code.</a>
5. <a href="#Report-results-and-analysis.">Report results and analysis.</a>

# Implement logistic regression likelihood.

Data is given as $D = {(\mathbf{x}_i, y_i):, i = 1...n}$, where $y_i \in \{-1, +1\}$, and $\mathbf{x}_i \in R^p$. In this case there are n samples and each sample has p features. <br \>

For logistic regression, 
* We have model parameters: $\mathbf{w} \in R^p$ for weight and a bias term $b$.
* For a sample x and its label y, $p(y|\mathbf{x}, \mathbf{w}, b) = \frac{1}{1+exp\{-y(\mathbf{w} \cdot \mathbf{x} + b)\}}$ 
* We can define $x' = \begin{bmatrix} 1\\ x \end{bmatrix}$, then $ \mathbf{w}' =  \begin{bmatrix} b\\ \mathbf{w} \end{bmatrix}$. Therefore the bias term is included in the weight vector. For notation brevity, we still use notations $x, \mathbf{w}$ as $x', \mathbf{w}'$. This can be implemented by numpy.concatenate function.
* Hence the first entry of the vector $w'$ is bias term and the rest are feature weights. In the code you can use w[0] to access the bias term and w[1:] to access the feature weights.

In [ ]:
import numpy as np
#We help you do the concatenate, so the first feature becomes the  bias term
train_data_pad = np.concatenate( ( np.ones((trainData.shape[0], 1)), trainData ), axis = 1 )
test_data_pad = np.concatenate( ( np.ones((testData.shape[0], 1)), testData ), axis = 1 )
valid_data_pad = np.concatenate( ( np.ones((validData.shape[0], 1)), validData ), axis = 1 )

## To-do: 
1. Given the data $D = {(\mathbf{x}_i, y_i)} $, write down the likelihood function ($L(\mathbf{w})$) of logistic regression. ** [1 pt] **
2. Take $\log$ of the likelihood function in (1), write down the log likelihood function. Hint: $\log$ will not cancel $\exp$. ** [1 pt] **
3. Add  ridge penalty in the log likelihood function (Let the weight of ridge penalty be $\alpha$). Hint: Do not include $w_0$ in the ridge term. ** [1 pt] **
4. Write a function to compute regularized log likelihood ** [1 pt] **

1. $ L(\mathbf{w}) =  $
2. $ LL(\mathbf{w}) = -\sum_i ... $
3. $ PLL(\mathbf{w}) = -\sum_i ...  - \frac{\alpha}{2}\sum_{j=1}^{p} ... $

In [ ]:
import numpy as np
def loglikelihood(w, X, y, alpha): 
    #compute loglikelihood for current w, b, given the data X, y
    #w is a vector, b is a scalr, X is a n*p matrix and y is a vector.
    tmp = 1. + np.exp( ... )
    return -np.sum( ... ) - (alpha/2.)*np.sum( ... )

In [ ]:
# testing
np.random.seed(1)
X = np.random.randn(2,3)
y = np.array([1,-1])
w = np.ones(3)
w[[1]] = -1;
loglikelihood(w, X, y, 1)


In [ ]:
#the values printed in this cell should be the same as the value printed in the previous cell.
print( -np.log(1+np.exp(-1*(X[0,0]-X[0,1]+X[0,2]))) - np.log(1+np.exp(1*(X[1,0]-X[1,1]+X[1,2]))) -1/2.*np.sum(w[1:]**2) )

<a href="#top_of_steps">top</a>

# Compute derivative of logistic regression.

In order to optimize the function, we want to take the derivative of the function, and update $\mathbf{w}$ according to the direction of the gradient.

## To-do:
1. Write down the derivative of the **penalized log likelihood function** for each $ w_j $. Hint: Remember that bias term is $w_0$ and treat it separately from the rest of $w_j$, $j\in\{1,...,p\}$ ** [1 pt] **
2. Write down the gradient of log likelihood function. Hint: You can express this in terms of probabilities. ** [1 pt] **
3. Update the loglikelihood function to return both the loglikelihood and the gradient. ** [1 pt] **

1. <br \>
$ \frac{\partial PLL(\mathbf{w})}{ \partial w_0} = \sum_i ...$ <br \>
$ \frac{\partial PLL(\mathbf{w})}{ \partial w_j} = \sum_i ...  - ..., j>0$ <br \>
<br \>
2. <br \>
$ \nabla PLL(\mathbf{w}) = \sum_i ...y_i\begin{bmatrix}  \\ \\ \vdots \\  \end{bmatrix} - \begin{bmatrix}  \\  \\ \vdots \\  \end{bmatrix} $

In [ ]:
import numpy as np
def loglikelihood(w, X, y, alpha): 
    #compute loglikelihood for current w, b, given the data X, y
    #w is a vector, b is a scalr, X is a n*p matrix and y is a vector.
    tmp = 1. + np.exp( ... )
    prob = 1./tmp
    X = X.T #X becomes a p*n matrix so the gradVal can be compute straight-forwardly.
    gradVal = np.dot(...,...)
    penalty = alpha/2.*np.sum(...)
    gradPenalty = -...
    gradPenalty[0] = ...;
    return -np.sum( np.log( tmp ) ) - penalty, gradVal + gradPenalty

<a href="#top_of_steps">top</a>

# Check gradient.

It is very important we know the derivative we computed is correctly. We can check it by comparing it with numerical answers.

In [1]:
# %load grad_check.py
def grad_check(f,xy0,delta=1e-6,tolerance=1e-7):
    f0,g0 = f(xy0)
    p = len(xy0)
    finite_diff = np.zeros(p)
    gradient_correct = True
    for i in range(p):
        xy1 = np.copy(xy0)
        xy2 = np.copy(xy0)
        xy1[i] = xy1[i] - 0.5*delta
        xy2[i] = xy2[i] + 0.5*delta
        f1,_ = f(xy1)
        f2,_ = f(xy2)
        finite_diff = (f2 - f1)/(delta)
        if (abs(finite_diff - g0[i])>tolerance):
            print("Broken partial",i," Finite Diff: ",finite_diff," Partial: ",g0[i])
            gradient_correct = False
    return gradient_correct

* We initialize the w vector

In [ ]:
w_init = np.random.randn( train_data_pad.shape[1] )*0.001
w_init[0] = 0

## To-do:
* Here is the code to test if your gradient computation is correct (If the result is true, you get **1 pt**)

In [ ]:
g = lambda xy0: loglikelihood(xy0, X=train_data_pad[:,:15], y=trainLabel, alpha=1)
grad_check( g, w_init[:15], delta=1e-6, tolerance=1e-5 )

<a href="#top_of_steps">top</a>

# Tweak gradient ascent code.

Here we provide the gradient ascent function.

In [ ]:
import matplotlib.pyplot as plt
%matplotlib inline
# %load gradient_ascent
def gradient_ascent(f,x,init_step,iterations):  
    f_val,grad = f(x)                           # compute function value and gradient 
    f_vals = [f_val]
    for it in range(iterations):                # iterate for a fixed number of iterations
        #print 'iteration %d' % it
        done = False                            # initial condition for done
        line_search_it = 0                      # how many times we tried to shrink the step
        step = init_step                        # reset step size to the initial size
        while not done and line_search_it<100:  # are we done yet?
            new_x = x + step*grad               # take a step along the gradient
            new_f_val,new_grad = f(new_x)       # evaluate function value and gradient
            if new_f_val<f_val:                 # did we go too far?
                step = step*0.95                # if so, shrink the step-size
                line_search_it += 1             # how many times did we shrank the step
            else:
                done = True                     # better than the last x, so we move on
        
        if not done:                            # did not find right step size
            print("Line Search failed.")
        else:
            f_val = new_f_val                   # ah, we are ok, accept the new x
            x = new_x
            grad = new_grad
            f_vals.append(f_val)
        plt.plot(f_vals)
    plt.xlabel('Iterations')
    plt.ylabel('Function value')
    return f_val, x

In [ ]:
np.random.seed(12345)
w_init = np.random.randn( train_data_pad.shape[1] )*0.001
w_init[0] = 0

## To-do:
* Try different init_step (1e-4, 1e-5, 1e-6) using the following code, report the final regularized log-likelihood values. **[1 pt]**

In [ ]:
def optimizeFn( init_step, iterations, alpha, w):
    g = lambda xy0: loglikelihood(xy0, train_data_pad, trainLabel, alpha)
    f_val, update_w = gradient_ascent( g, w, init_step, iterations )
    return f_val, update_w

In [ ]:
print 'This should take about 6 seconds.'
start = time.time()
f_val, update_w=optimizeFn( init_step = 1e-4, iterations=100, alpha=0, w = w_init) #set init_step to 1e-4, 1e-5, 1e-6
end = time.time()
print 'Time elapsed (seconds):', end-start
print 'final log-likelihood = %f\n' % (f_val)

Final regularized log-likelihood values for (1e-4, 1e-5, 1e-6) are: ...

<a href="#top_of_steps">top</a>

# Report results and analysis.

To evaluate the results, we need to have a prediction function, that uses the model we trained to predict the comment is positive and negative.

## To-do:
1. Implement the prediction function. It should take as inputs feature weights and feature matrix. It should return vector of labels. **[1 pt]**
2. Try different alpha (1000, 2000, 3000), and report which alpha produces the model that has the best accuracy on the validation set **[1 pt]**
2. **[optional]** Report one sample that is classified wrong with high probabilites (> 90%). **[1 pt]**
3. **[optional]** Report the words (entries in vocab_list associated with that feature) that cause the sample reported in (2) classify wrong. Note that weight w[i] correponds to word vocab_list[i-1], because we included bias term in w.**[1 pt]**

In [ ]:
def prediction(w, validData ):
    prob = 1./(1+np.exp(... ) );
    res = np.zeros(validData.shape[0])
    res[prob>=...] = ...
    res[prob<...] = ...
    return res

In [ ]:
#see the accuracy on the validation set
#when init_step=1e-5, the model has the best accuracy in the validation set
f_val, update_w=optimizeFn( init_step = 1e-5, iterations=100, alpha=1000, w=w_init) #try different alphas [1000, 2000, 3000]
pred = prediction(update_w, valid_data_pad)
print( 'accuracy on the validation set {:.2f}%'.format( 100.*np.mean(pred==validLabel)) )

The best alpha is ..., and the accuracy of this alpha is: ...

* Report one sample (sample index in the validation data set) that is classified wrong with high probabilites

In [ ]:
wrong_idx = np.nonzero( validLabel != pred )[0] #use this command to get the samples that are predicted wrong

In [ ]:
#implement the function to compute probability
def computeProb(w, validData ):
    prob = 1./(1+np.exp(... ) )
    return prob

In [ ]:
#get the samples that are classified wrong and with probabilites > 0.9
probs = computeProb(update_w, valid_data_pad)
wrong_idx_high = ...

The sample index is ...

* Report the words that cause the sample reported in (2) classify wrong.

In [ ]:
#Use this function to get the most important words for each sample index
#This function returns a list of top 10 words that influence the prediction.
def getMostImportantFeatures( sampleIdx, validData, update_w, vocab_list ):
    confusedList = []
    intensity = validData[sampleIdx,:]*update_w
    tmp = np.argsort( np.abs(intensity[0,:]) )[::-1]
    for j in np.arange(10):
        confusedList.append(vocab_list[tmp[j]-1])
    return confusedList

In [ ]:
confusedList = getMostImportantFeatures( sampleIdx, valid_data_pad, update_w, vocab_list) #use the sample index got from the previous result
confusedList

In [15]:
#load file ids
if not os.path.isfile('train_id.pgz'):
    U.urlretrieve( "https://sakai.unc.edu/access/content/group/c4f84923-328b-429b-a8dc-a340b0284e41/HW1/train_id.pgz", "train_id.pgz" );
train_id = pickle.load( gzip.open( "train_id.pgz", "rb" ) )
valid_id = train_id[10000:15000]

* Retrieve the whole review and check if it is hard to classify

In [24]:
fileName = valid_id[100]
fileUrl = "https://wwwx.cs.unc.edu/Courses/comp755-f18/hw1/reviews/" + fileName + '.txt'

In [25]:
U.urlretrieve(fileUrl, fileName)

('731_9', <http.client.HTTPMessage at 0x10668e780>)

<a href="#top_of_steps">top</a>